name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hihidrdi/mik32:latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        ./ci/build.sh
    - name: Run tests
      run: |
        ./ci/run_tests.sh
